# This workflow will:
# - build and push a docker image using  skaffold
# - always make a pull request in the deploy repo to update staging & auto merge it
# - on release tags (v...), also make a draft pull request to update prod

# It is designed to be called from the source repo.
# Assumes the deploy repo is named {source_code_repo}-deploy

name: Continous Deployment

on:
  workflow_call:

jobs:
  container:
    runs-on: ubuntu-latest
    concurrency:
      group: cd-container

    permissions:
      packages: write
      contents: read

    env:
      REGISTRY: ghcr.io

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            accept-flake-config = true

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache/restore skaffold
        uses: actions/cache@v3
        with:
          path: ~/.skaffold/
          key: skaffold-${{ github.sha }}
          restore-keys: |
            skaffold-

      - name: Build and push container image
        id: skaffold
        env:
          SKAFFOLD_DEFAULT_REPO: ${{ env.REGISTRY }}/${{ github.repository }}
          SKAFFOLD_BUILDX_ARGS: "--cache-to type=gha,mode=max,ignore-error=true --cache-from type=gha"
        run: nix develop --impure --command skaffold build -p app --file-output built-images.json

      - name: Upload Skaffold build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: skaffold-build-artifacts
          path: built-images.json

  update:
    runs-on: ubuntu-latest
    needs: container
    concurrency:
      group: cd-update

    steps:
      - name: Get a token as lco-deploy-bot
        uses: actions/create-github-app-token@v1
        id: lco-deploy-bot
        with:
          app-id: ${{ secrets.LCO_DEPLOY_BOT_APP_ID }}
          private-key: ${{ secrets.LCO_DEPLOY_BOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            accept-flake-config = true

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Configure Git to use lco-deploy-bot token
        run: |
          git config --global url."https://x-access-token:${{ steps.lco-deploy-bot.outputs.token }}@github.com".insteadOf "https://github.com"

      - name: Download Skaffold build artifacts
        uses: actions/download-artifact@v4
        with:
          name: skaffold-build-artifacts

      - name: Gather commit/PR metadata
        id: common
        uses: actions/github-script@v7
        with:
          script: |
            const botName = "${{ vars.LCO_DEPLOY_BOT_APP_NAME }}[bot]";
            const botActorId = "${{ vars.LCO_DEPLOY_BOT_APP_ACTOR_ID }}";
            const botEmail = `${botActorId}+${botName}@users.noreply.github.com`;

            const commitMessage = context.payload.head_commit.message;
            const commitLines = commitMessage.split("\n");
            const commitSubject = commitLines.at(0);
            const commitBody = commitLines.slice(1).join("\n");

            const commitUrl = context.payload.head_commit.url;

            const coAuthoredBy = "Co-authored-by: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>";

            let prCommitTitle = commitSubject;

            const prCommitBodyElms = [];
            const prBodyElms = [];

            if (context.eventName === "release") {
              const release = context.payload.release;

              prCommitTitle = `release: ${release.name}`;

              const ownerRepo = `${context.reop.owner}/${context.repo.repo}`;
              const releaseId = `${ownerRepo}/${release.tag_name}`;
              const releaseNotesTemplate = `{{ githubRelease "${releaseId}" | expandGithubLinks "${ownerRepo}" }}`;

              prCommitBodyElms.push(releaseNotesTemplate);
              prBody.push(releaseNotesTemplate);
            } else {
              prCommitBodyElms.push(`Source-commit: ${commitUrl}`, commitBody);
              prBodyElms.push(`Source-commit: ${commitUrl}`, commitBody);
            }

            prCommitBodyElms.push(coAuthoredBy);
            prBodyElms.push(`Triggered-by: @${context.actor}`);

            prCommitBody = prCommitBodyElms.filter(x => x).join("\n\n");
            prBody = prBodyElms.filter(x => x).join("\n<br>\n");

            core.setOutput("botName", botName);
            core.setOutput("botEmail", botEmail);
            core.setOutput("prCommitTitle", prCommitTitle);
            core.setOutput("prCommitBody", prCommitBody);
            core.setOutput("prBody", prBody);

      - name: Create staging PR
        run: |
          nix run github:LCOGT/devenv-k8s#octopilot -- \
            --fail-on-error --log-level debug \
            --github-auth-method app \
            --github-app-id '${{ secrets.LCO_DEPLOY_BOT_APP_ID }}' \
            --github-installation-id '${{ secrets.LCO_DEPLOY_BOT_APP_INSTALL_ID }}' \
            --github-privatekey '${{ secrets.LCO_DEPLOY_BOT_APP_PRIVATE_KEY }}' \
            \
            --repo '${{ github.repository }}-deploy' \
            \
            --update 'exec(cmd=nix,args=develop --impure --command cd-update-staging `${{ github.workspace }}/built-images.json` `${{ github.sha }}`)' \
            \
            --git-branch-prefix 'octopilot-staging-' \
            --git-author-name '${{ steps.common.outputs.botName }}' \
            --git-author-email '${{ steps.common.outputs.botEmail }}' \
            --git-committer-name '${{ steps.common.outputs.botName }}' \
            --git-committer-email '${{ steps.common.outputs.botEmail }}' \
            --git-commit-title 'staging: ${{ steps.common.outputs.prCommitTitle }}' \
            --git-commit-body  '${{ steps.common.outputs.prCommitBody }}' \
            --git-commit-footer '' \
            \
            --pr-base-branch main \
            --pr-labels octopilot,staging \
            --pr-assignees '${{ github.actor }}' \
            --pr-title 'staging: ${{ steps.common.outputs.prCommitTitle }}' \
            --pr-body '${{ steps.common.outputs.prBody }}' \
            --pr-merge \
            --pr-merge-auto \
            --pr-merge-auto-wait \
            --output-results staging-pr.json

      - name: Annotate w/ staging PR
        uses: actions/github-script@v7
        with:
          script: |
            const { readFile } = require("fs/promises");
            const data = JSON.parse(await readFile("staging-pr.json", "utf8"));

            const pr = data.repos[0].pr;
            const description = `Staging deploy PR #${pr.number}`;

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: "success",
              context: "cd/staging/pr",
              description: description,
              target_url: pr.url
            });

            core.summary.addLink(description, pr.url);
            core.summary.write();
